views.py
from flask import Blueprint, render_template, flash, current_app, request, url_for, redirect
from flask_paginate import Pagination, get_page_parameter

from api import JsonMethods
from forms import AddApiForm, EditApiForm, AddEndpointForm, EditEndpointForm, AddFieldForm, EditFieldForm
from utils import paginate
from config import Globals

views = Blueprint('views', __name__)

@views.route('/')
def list_apis():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    apis = JsonMethods.get_apis(page=page)
    total = JsonMethods.get_apis_count().get('count')
    pagination = Pagination(
        page=page, per_page=Globals.ITEM_PER_PAGE,
        total=total, record_name='apis', css_framework='bootstrap4'
    )
    edit_api_form = EditApiForm()
    add_endpoint_form = AddEndpointForm()
    return render_template(
        'apis_listing.html', apis=apis, pagination=pagination,
        edit_api_form=edit_api_form, add_endpoint_form=add_endpoint_form
    )

@views.route('/<int:id>')
def detail_api(id):
    page = request.args.get('page', type=int, default=1)
    api = JsonMethods.get_api(id)
    endpoints = api.get('endpoints')
    total = len(endpoints)
    if total:
        try:
            endpoints = paginate(
                endpoints, Globals.ITEM_PER_PAGE,
                page, lambda x: int(x.get('id'))
            )
        except:
            flash('There is no %d pages of endpoints for API %d' % (page, api_id), 'danger')
            return redirect(url_for('views.list_endpoints'))

    pagination = Pagination(
        page=page, per_page=Globals.ITEM_PER_PAGE,
        total=total, record_name='endpoints', css_framework='bootstrap4'
    )
    edit_api_form = EditApiForm()
    add_endpoint_form = AddEndpointForm()
    edit_endpoint_form = EditEndpointForm()
    add_field_form = AddFieldForm()
    return render_template(
        'api_detailing.html', api=api, endpoints=endpoints, pagination=pagination,
        edit_api_form=edit_api_form, add_endpoint_form=add_endpoint_form,
        edit_endpoint_form=edit_endpoint_form, add_field_form=add_field_form
    )

@views.route('/search')
def search_by_tags():
    tags = request.args.get('tags')
    apis = JsonMethods.get_apis(tags=tags)
    endpoints = JsonMethods.get_endpoints(tags=tags)
    edit_api_form = EditApiForm()
    add_endpoint_form = AddEndpointForm()
    edit_endpoint_form = EditEndpointForm()
    add_field_form = AddFieldForm()
    return render_template(
        'search_by_tags.html', apis=apis, endpoints=endpoints,
        edit_api_form=edit_api_form, add_endpoint_form=add_endpoint_form,
        edit_endpoint_form=edit_endpoint_form, add_field_form=add_field_form
    )

@views.route('/add', methods=['GET', 'POST'])
def add_api():
    form = AddApiForm()
    if form.validate_on_submit():
        response = JsonMethods.add_api(
            label=form.label.data, url=form.url.data,
            description=form.description.data, tags=form.tags.data
        )
        if response.get('status') == 'ok':
            flash(response.get('message'), 'success')
            id = response.get('id')
            return redirect(url_for('views.detail_api', id=id))
        else:
            flash(response.get('message'), 'danger')
            return redirect(url_for('views.add_api'))
    return render_template('api_adding.html', form=form)

@views.route('/edit/<int:id>', methods=['POST'])
def edit_api(id):
    form = EditApiForm()
    if form.validate_on_submit():
        response = JsonMethods.edit_api(
            id, label=form.label.data, url=form.url.data,
            description=form.description.data, tags=form.tags.data
        )
        if response.get('status') == 'error':
            flash(response.get('message'), 'danger')
        else:
            flash(response.get('message'), 'success')
    else:
        flash(
            "The following errors occured while editing api #%s: %s"%
            (id, form.errors), 'danger'
        )
    return redirect(url_for('views.detail_api', id=id))

@views.route('/add_endpoint/<int:id>', methods=['POST'])
def add_endpoint(id):
    form = AddEndpointForm()
    if form.validate_on_submit():
        response = JsonMethods.add_endpoint(
            id,label=form.label.data, url=form.url.data,
            description=form.description.data, tags=form.tags.data
        )
        if response.get('status') == 'error':
            flash(response.get('message'), 'danger')
        else:
            flash(response.get('message'), 'success')
    else:
        flash(
            "The following errors occured while adding an endpoint to api #%s: %s"%
            (id, form.errors), 'danger'
        )
    return redirect(url_for('views.detail_api', id=id))

@views.route('/delete/<int:id>', methods=['POST'])
def delete_api(id):
    response = JsonMethods.delete_api(id)
    if response.get('status')=='error':
        flash(response.get('message'), 'danger')
    else:
        flash(response.get('message'), 'success')
    return redirect(url_for('views.list_apis'))

@views.route('/endpoints')
def list_endpoints():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    endpoints = JsonMethods.get_endpoints(page=page)
    total = JsonMethods.get_endpoints_count().get('count')
    pagination = Pagination(
        page=page, per_page=Globals.ITEM_PER_PAGE,
        total=total, record_name='endpoints', css_framework='bootstrap4'
    )
    edit_endpoint_form = EditEndpointForm()
    add_field_form = AddFieldForm()
    return render_template(
        'endpoints_listing.html', endpoints=endpoints, pagination=pagination,
        edit_endpoint_form=edit_endpoint_form, add_field_form=add_field_form
    )

@views.route('/edit_endpoint/<int:id>', methods=['POST'])
def edit_endpoint(id):
    form = EditEndpointForm()
    if form.validate_on_submit():
        response = JsonMethods.edit_endpoint(
            id, label=form.label.data, url=form.url.data,
            description=form.description.data, tags=form.tags.data
        )
        if response.get('status') == 'error':
            flash(response.get('message'), 'danger')
        else:
            flash(response.get('message'), 'success')
    else:
        flash(
            "The following errors occured while editing endpoint #%s: %s"%
            (id, form.errors), 'danger'
        )
    return redirect(url_for('views.detail_endpoint', id=id))

@views.route('/endpoints/delete/<int:id>', methods=['POST'])
def delete_endpoint(id):
    response = JsonMethods.delete_endpoint(id)
    if response.get('status')=='error':
        flash(response.get('message'), 'danger')
    else:
        flash(response.get('message'), 'success')
    return redirect(url_for('views.list_endpoints'))

@views.route('/endpoints/<int:id>')
def detail_endpoint(id):
    endpoint = JsonMethods.get_endpoint(id)
    add_field_form = AddFieldForm()
    edit_endpoint_form = EditEndpointForm()
    edit_field_form = EditFieldForm()
    return render_template(
        'endpoint_detailing.html', endpoint=endpoint, add_field_form=add_field_form,
        edit_endpoint_form=edit_endpoint_form, edit_field_form=edit_field_form
    )

@views.route('/endpoints/<int:id>/add_field', methods=['POST'])
def add_field(id):
    form = AddFieldForm()
    if form.validate_on_submit():
        response = JsonMethods.add_field(
            id, label=form.label.data, field_type=form.type.data,
            required=form.required.data, default=form.default.data,
            description=form.description.data
        )
        if response.get('status') == 'error':
            flash(response.get('message'), 'danger')
        else:
            flash(response.get('message'), 'success')
    else:
        flash(
            "The following errors occured while adding a field to endpoint #%s: %s" %
            (id, form.errors), 'danger'
        )

    return redirect(url_for('views.detail_endpoint', id=id))

@views.route('/fields/<int:id>/edit_field', methods=['POST'])
def edit_field(id):
    form = EditFieldForm()
    field = JsonMethods.get_field(id)
    endpoint_id = int(field.get('endpoint_id'))
    if form.validate_on_submit():
        response = JsonMethods.edit_field(
            id, label=form.label.data, field_type=form.type.data,
            required=form.required.data, default=form.default.data,
            description=form.description.data
        )
        if response.get('status') == 'error':
            flash(response.get('message'), 'danger')
        else:
            flash(response.get('message'), 'success')
    else:
        flash(
            "The following errors occured while editing field #%s: %s"%
            (id, form.errors), 'danger'
        )
    return redirect(url_for('views.detail_endpoint', id=endpoint_id))

@views.route('/fields/<int:id>/delete', methods=['POST'])
def delete_field(id):
    field = JsonMethods.get_field(id)
    endpoint_id = int(field.get('endpoint_id'))
    response =  JsonMethods.delete_field(id)
    if response.get('status')=='error':
        flash(response.get('message'), 'danger')
    else:
        flash(response.get('message'), 'success')
    return redirect(url_for('views.detail_endpoint', id=endpoint_id))

templates/macros/api_buttons.html
{% from "macros/modal_form.html" import modal_form %}
{% from "macros/delete_modal_form.html" import  delete_modal_form %}

{% macro api_buttons(api, edit_api_form, add_endpoint_form) %}

    {% set url_endpoint=request.url_rule.endpoint %}

    <style>
        .api-buttons a{
            font-size: 12px;
        }
    </style>

    <div class="api-buttons">
        {% if url_endpoint!="views.detail_api" %}
            <a href="{{ url_for('views.detail_api', id=api.id) }}" class="btn btn-success">
                <i class="fa fa-list-ul"></i> Details
            </a>
        {% endif %}

        <!-- Add Endpoint -->
        {% set html_id="add-endpoint-to-api-"+api.id|string %}
        {% set button_text="Add Endpoint" %}
        {% set button_color="info" %}
        {% set head_text="Add endpoint to API #" + api.id|string + " " + api.label %}
        {% set action=url_for('views.add_endpoint', id=api.id) %}
        {{ modal_form(html_id=html_id, button_text=button_text, button_color=button_color, head_text=head_text, form=add_endpoint_form, action=action) }}

        <!-- Edit API -->
        {% set html_id="edit-api-"+api.id|string %}
        {% set button_text="Edit" %}
        {% set button_color="secondary" %}
        {% set head_text="#" + api.id|string + " " + api.label %}
        {% set action=url_for('views.edit_api', id=api.id) %}
        {{ modal_form(html_id=html_id, button_text=button_text, button_color=button_color, head_text=head_text, form=edit_api_form, action=action, data=api) }}

        <!-- Delete API -->
        {% set html_id="delete-api-"+api.id|string %}
        {% set message="Do you want to delete API " + api.url %}
        {% set action=url_for('views.delete_api', id=api.id) %}
        {% set head_text="#" + api.id|string + " " + api.label %}
        {{ delete_modal_form(html_id=html_id, button_text="Delete", head_text=head_text, message=message, action=action )}}
    </div>

{% endmacro %}

templates/macros/api_item.html
{% from "macros/api_buttons.html" import api_buttons %}

{% macro api_item(api, edit_api_form, add_endpoint_form) %}

<div class="card mb-2">
    <div class="card-header">
        {{api.label}}
    </div>
    <div class="card-body">
        <div class="card-title d-inline">
            <h6 class="d-inline mb-0" >{{api.url}} </h6>
            {% for tag in api.tags %}
                <span class="badge badge-primary d-inline ml-1">{{tag}} </span>
            {% endfor %}
        </div>

        <p class="card-text"><small>{{api.description}}</small></p>

        {{ api_buttons(api, edit_api_form, add_endpoint_form) }}
    </div>
</div>

{% endmacro %}

templates/macros/apis_list.html
{% from "macros/api_item.html" import api_item %}

{% macro apis_list(apis, edit_api_form, add_endpoint_form) %}

<h5 class="card-title mt-3">APIs List</h5>
<div class="card-list mt-3">
	{% if not apis|length %}
		<h5 class="card-title mt-3">NA</h5>
	{% endif %}

	{% for api in apis %}
		{{ api_item(api, edit_api_form, add_endpoint_form) }}
	{% endfor %}
</div>

{% endmacro %}

templates/macros/endpoint_buttons.html
{% from "macros/modal_form.html" import modal_form %}
{% from "macros/delete_modal_form.html" import  delete_modal_form %}

{% macro endpoint_buttons(endpoint, edit_endpoint_form, add_field_form) %}

    {% set url_endpoint=request.url_rule.endpoint %}

    <style>
        .endpoint-buttons a{
            font-size: 12px;
        }
    </style>

     <div class="endpoint-buttons">
            {% if url_endpoint!="views.detail_endpoint" %}
                <a href="{{ url_for('views.detail_endpoint', id=endpoint.id) }}" class="btn btn-success">
                    <i class="fa fa-list-ul"></i> Details
                </a>
            {% endif %}

            <!-- Add Field -->
            {% set html_id="add-field-to-endpoint-"+endpoint.id|string %}
            {% set button_text="Add Field" %}
            {% set button_color="info" %}
            {% set head_text="Add Field to endpoint #" + endpoint.id|string + " " + endpoint.label %}
            {% set action=url_for('views.add_field', id=endpoint.id) %}
            {{ modal_form(html_id=html_id, button_text=button_text, button_color=button_color, head_text=head_text, form=add_field_form, action=action) }}

            <!-- Edit Endpoint -->
            {% set html_id="edit-endpoint-"+endpoint.id|string %}
            {% set button_text="Edit Endpoint" %}
            {% set button_color="secondary" %}
            {% set head_text="#" + endpoint.id|string + " " + endpoint.label %}
            {% set action=url_for('views.edit_endpoint', id=endpoint.id) %}
            {{ modal_form(html_id=html_id, button_text=button_text, button_color=button_color, head_text=head_text, form=edit_endpoint_form, action=action, data=endpoint) }}

            <!-- Delete Endpoint -->
            {% set html_id="delete-endpoint-"+endpoint.id|string %}
            {% set message="Do you want to delete Endpoint " + endpoint.url %}
            {% set action=url_for('views.delete_endpoint', id=endpoint.id) %}
            {% set head_text="#" + endpoint.id|string + " " + endpoint.label %}
            {{ delete_modal_form(html_id=html_id, button_text="Delete", head_text=head_text, message=message, action=action )}}
        </div>

{% endmacro %}

templates/macros/endpoint_item.html
{% from "macros/endpoint_buttons.html" import endpoint_buttons %}

{% macro endpoint_item(endpoint, edit_endpoint_form, add_field_form) %}

<div class="card mb-2">
    <div class="card-header">
        {{endpoint.api_item.label}}: {{endpoint.label}}
    </div>
    <div class="card-body">
        <div class="card-title d-inline">
            <h6 class="d-inline mb-0">{{endpoint.api_item.url}}{{endpoint.url}} </h6>
            {% for tag in endpoint.tags %}
                <span class="badge badge-primary d-inline ml-1">{{tag}} </span>
            {% endfor %}
        </div>

        <p class="card-text"><small>{{endpoint.description}}</small></p>

        {{ endpoint_buttons(endpoint, edit_endpoint_form, add_field_form) }}
    </div>
</div>

{% endmacro %}

templates/macros/endpoints_list.html
{% from "macros/endpoint_item.html" import endpoint_item %}

{% macro endpoints_list(endpoints, edit_endpoint_form, add_field_form) %}

<h5 class="card-title mt-3">Endpoints List:</h5>
<div class="card-list mt-3">
	{% if not endpoints|length %}
		<h5 class="card-title mt-3">NA</h5>
	{% endif %}

	{% for endpoint in endpoints %}
		{{ endpoint_item(endpoint, edit_endpoint_form=edit_endpoint_form, add_field_form=add_field_form) }}
	{% endfor %}
</div>

{% endmacro %}

templates/macros/field_buttons.html
{% from "macros/modal_form.html" import modal_form %}
{% from "macros/delete_modal_form.html" import  delete_modal_form %}

{% macro field_buttons(field, edit_field_form) %}

    <style>
        .field-buttons a{
            font-size: 12px;
        }
    </style>

     <div class="field-buttons">
            <!-- Edit Field -->
            {% set html_id="edit-field-"+field.id|string %}
            {% set button_text="Edit" %}
            {% set button_color="secondary" %}
            {% set head_text="Field " + field.label %}
            {% set action=url_for('views.edit_field', id=field.id) %}
            {{ modal_form(html_id=html_id, button_text=button_text, button_color=button_color, head_text=head_text, form=edit_field_form, action=action, data=field) }}

            <!-- Delete Field -->
            {% set html_id="delete-field-"+field.id|string %}
            {% set message="Do you want to delete Field " + field.label %}
            {% set action=url_for('views.delete_field', id=field.id) %}
            {% set head_text="Field " + field.label %}
            {{ delete_modal_form(html_id=html_id, button_text="Delete", head_text=head_text, message=message, action=action )}}
        </div>

{% endmacro %}

templates/macros/fields_table.html
{% from "macros/field_buttons.html" import field_buttons %}

{% macro fields_table(fields, edit_field_form) %}

    <style>
        @media screen and (max-width: 991px) {
            .fields-table{
                display: block;
                overflow-x: auto;
                white-space: nowrap;
            }
        }
    </style>

    <table class="table fields-table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Required</th>
                <th scope="col">Description</th>
                <th scope="col">Default</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for field in fields %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td>{{ field.label }}</td>
                    <td>{{ field.type }}</td>
                    <td>{{ field.required }}</td>
                    <td>{{ field.description }}</td>
                    <td>{{ field.default }}</td>
                    <td>
                        {{ field_buttons(field, edit_field_form) }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endmacro %}

templates/macros/flash_messages.html
{% macro flash_messages() %}

<div class="flash-messages mt-2 col-9 col-lg-10">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                <button type="button" class="close close-flash" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endwith %}
</div>

<script>
    $(document).ready(function(){
        $(".close-flash").click(function(){
            $(this).parent().remove()
        });
    });
</script>

{% endmacro %}

templates/macros/leftnav.html
{% macro leftnav() %}

<style>
    .nav-side-menu {
        overflow: auto;
        cursor: pointer;
        position: fixed;
        top: 0;
        bottom: 0;
        left: 0;
        z-index: 100;
        padding: 48px 0 0;
        background-color: #2e353d;
        box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
        color: #e1ffff;
    }
    .nav-side-menu .toggle-btn {
        display: none;
    }
    .nav-side-menu ul,
    .nav-side-menu li {
        list-style: none;
        padding: 0px;
        margin: 0px;
        line-height: 35px;
        cursor: pointer;
    }
    .nav-side-menu ul :not(collapsed) .arrow:before,
    .nav-side-menu li :not(collapsed) .arrow:before {
        font-family: FontAwesome;
        content: "\f078";
        display: inline-block;
        padding-left: 10px;
        padding-right: 10px;
        vertical-align: middle;
        float: right;
    }
    .nav-side-menu ul .active,
    .nav-side-menu li .active {
        border-left: 3px solid #d19b3d;
        background-color: #4f5b69;
    }
    .nav-side-menu ul .sub-menu li.active,
    .nav-side-menu li .sub-menu li.active {
        color: #d19b3d;
    }
    .nav-side-menu ul .sub-menu li.active a,
    .nav-side-menu li .sub-menu li.active a {
        color: #d19b3d;
    }
    .nav-side-menu ul .sub-menu li,
    .nav-side-menu li .sub-menu li {
        background-color: #343A40;
        border: none;
        line-height: 28px;
        border-bottom: 1px solid #23282e;
        margin-left: 0px;
    }
    .nav-side-menu ul .sub-menu li:hover,
    .nav-side-menu li .sub-menu li:hover {
        background-color: #020203;
    }
    .nav-side-menu ul .sub-menu li a{
        display: block;
        width: 100%;
    }
    .nav-side-menu ul .sub-menu li a:before,
    .nav-side-menu li .sub-menu li a:before {
        font-family: FontAwesome;
        content: "\f105";
        display: inline-block;
        padding-left: 10px;
        padding-right: 10px;
        vertical-align: middle;
    }
    .nav-side-menu li {
        padding-left: 0px;
        border-left: 3px solid #2e353d;
        border-bottom: 1px solid #23282e;
    }
    .nav-side-menu li a {
        text-decoration: none;
        color: #e1ffff;
    }
    .nav-side-menu li a i {
        padding-left: 10px;
        width: 20px;
        padding-right: 20px;
    }
    .nav-side-menu li:hover {
        border-left: 3px solid #d19b3d;
        background-color: #4f5b69;
        -webkit-transition: all 1s ease;
        -moz-transition: all 1s ease;
        -o-transition: all 1s ease;
        -ms-transition: all 1s ease;
        transition: all 1s ease;
    }
    @media (max-width: 767px) {
        .toggle-leftnav-btn{
            display: block;
            cursor: pointer;
            position: fixed;
            left: 10px;
            top: 5px;
            z-index: 1040 !important;
            padding: 1px;
            width: 40px;
            text-align: center;
        }
        .nav-side-menu{
            width: 40%;
        }
    }
</style>

{% set url_path=request.path %}
{% set url_endpoint=request.url_rule.endpoint %}

<button class="btn btn-outline-dark toggle-leftnav-btn">
    <i class="fa fa-bars fa-2x"></i>
</button>
<div class="nav-side-menu col-md-3 col-lg-2 d-md-block collapse" id="left-navside">
    <ul id="menu-content">
        <!-- APIs -->
        <li  data-toggle="collapse" data-target="#apis"
             class="{{ 'active' if url_path.startswith('/apis') or url_endpoint=='views.list_apis' }}"
        >
            <a href="#">
                <i class="fa fa-gift fa-lg"></i> APIs <span class="d-sm-inline d-md-none d-lg-inline arrow"></span>
            </a>
        </li>
        <ul class="sub-menu collapse" id="apis">
            <li class="{{ 'active' if url_endpoint=='views.list_apis' }}">
                <a href="{{ url_for('views.list_apis') }}">List</a>
            </li>
            <li class="{{ 'active' if url_endpoint=='views.add_api' }}">
                <a href="{{ url_for('views.add_api') }}">Add</a>
            </li>
        </ul>

        <!-- Endpoints -->
        <li  data-toggle="collapse" data-target="#endpoints" class="{{ 'active' if url_path.startswith('/endpoints') }}">
            <a href="#">
                <i class="fa fa-gift fa-lg"></i> Endpoints <span class="d-sm-inline d-md-none d-lg-inline arrow"></span>
            </a>
        </li>
        <ul class="sub-menu collapse" id="endpoints">
            <li class="{{ 'active' if url_endpoint=='views.list_endpoints' }}">
                <a href="{{ url_for('views.list_endpoints') }}">List</a>
            </li>
        </ul>

        <!-- Last request -->
        <li class="{{ 'active' if url_path.startswith('/request') }}">
            <a href="#">
                <i class="fa fa-users fa-lg"></i> Request
            </a>
        </li>
    </ul>
</div>

<script>
    $(document).ready(function(){

        $(document).mouseup(function(e){
            if ($(window).width() <768){
                var container = $("#left-navside");
                var button = $(".toggle-leftnav-btn");
                if (!container.is(e.target) && container.has(e.target).length === 0 &&
                    !button.is(e.target) && button.has(e.target).length === 0
                )
                {
                    container.slideUp();
                }
            }
        });

        $(".toggle-leftnav-btn").click(function(){
            $("#left-navside").slideToggle();
        });
    });
</script>

{% endmacro %}

templates/macros/modal_form.html
{% from "macros/render_form.html" import render_form %}

{% macro modal_form(html_id, button_text, button_color, head_text, form, action, data='') %}

<a href="#" data-toggle="modal" data-target="#{{ html_id }}" class="btn btn-{{button_color}}">
    <i class="fa fa-pencil"></i> {{button_text}}
</a>
<div class="modal fade" id="{{ html_id }}" tabindex="-1" role="dialog" aria-labelledby="modal-label-{{html_id}}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-label-{{html_id}}">{{head_text}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ render_form(form, action_url=action, action_text=button_text, data=data) }}
            </div>
        </div>
    </div>
</div>

{% endmacro %}

templates/macros/navbar.html
{% macro navbar() %}

<style>
    nav.navbar #search-btn{
        z-index: 2;
    }
    #search-form-secondary{
        position: absolute;
        top: 0;
        padding: 48px 0 0;
        z-index: 1;
    }
    #search-form-secondary button{
        width: 15%;
    }
    #search-form-secondary input{
        width: 85%;
    }
    .no-text-decoration{
        text-decoration: none !important;
    }
    #login-logout li:hover{
        background: #17A2B8;
    }
    #login-logout li a{
        color: #343a40;
    }
    #login-logout li a:hover{
        color: #FFF;
    }
    #login-logout .dropdown-menu{
        margin-left: -130%;
    }
</style>

<nav class="navbar navbar-dark bg-info flex-md-nowrap py-1 px-0 shadow fixed-top">
    <!-- The brand -->
    <div class="col-4 col-sm-3 col-lg-2 mr-0 text-white navbar-brand text-center">
        <div class="d-none d-md-block">
            Dashboard
        </div>
    </div>

    <!-- Searchbar -->
    <form class="form-inline col-4 col-sm-6 col-lg-8 my-0 pl-3" action="{{ url_for('views.search_by_tags') }}" method="get" enctype="multipart/form-data">
        <input maxlength="400" name="tags" class="form-control mr-sm-2 col-lg-11 col-md-10 col-9 d-sm-block d-none" type="search" placeholder="Search by tags" aria-label="Search">
        <button id="search-btn" class="btn btn-outline-dark mx-auto mx-sm-0" type="submit"><i class="fa fa-search"></i></button>
    </form>
    <form id="search-form-secondary" class="form-inline w-100" action="{{ url_for('views.search_by_tags') }}" method="get" enctype="multipart/form-data" style="display: none;">
        <input maxlength="400" name="tags" class="form-control" type="search" placeholder="Search by tags" aria-label="Search">
        <button id="search-btn-secondary" class="btn btn-outline-dark" type="submit">GO!</button>
    </form>

    <!-- Login/logout -->
    <div id="login-logout" class="px-3 col-4 col-sm-3 col-lg-2">
        <div class="navbar-text btn-group float-right">
            <a href="#" class="dropdown-toggle no-text-decoration" data-toggle="dropdown" role="button" aria-expanded="false">
                <i class="fa fa-user"></i>
                {% if current_user.is_authenticated %}
                    {% if current_user.first_name -%}
                        {{ current_user.first_name }}
                    {% else -%}
                        {{ current_user.email }}
                    {%- endif %}
                {% else %}
                    Guest
                {% endif %}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                {% if current_user.has_role('superuser') %}
                    <li class="px-2 mx-2">
                        <a class="no-text-decoration" href="{{ url_for('admin.index') }}">
                            Go to Admin
                        </a>
                    </li>
                {% endif %}
                <li class="px-2 mx-2 no-text-decoration">
                    {% if current_user.is_authenticated %}
                        <a class="no-text-decoration" href="{{ url_for('security.logout') }}">
                            Logout
                        </a>
                    {% else %}
                        <a class="no-text-decoration" href="{{ url_for('security.login') }}">
                            Login
                        </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<script>
    $(document).ready(function(){
        $("#search-btn").click(function(e){
            if ($(window).width() < 576){
                e.preventDefault();
                $("#search-form-secondary").toggle();
            }
        });

        $(document).mouseup(function(e){
            if ($(window).width() <576){
                var container = $("#search-form-secondary");
                var button = $("#search-btn");
                if (!container.is(e.target) && container.has(e.target).length === 0 &&
                    !button.is(e.target) && button.has(e.target).length === 0
                )
                {
                    container.hide();
                }
            }
        });

        $(window).resize(function(){
            if ($(window).width() >= 576){
                $("#search-form-secondary").hide();
            }
        });
    });
</script>

{% endmacro %}